{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "368cff42",
   "metadata": {},
   "outputs": [],
   "source": [
    "from pyspark import SparkConf\n",
    "from pyspark.sql import SparkSession\n",
    "\n",
    "# Removing hard coded password - using os module & open to import them from creds.txt file\n",
    "import os\n",
    "import sys\n",
    "\n",
    "# Your job run a data cleaning code below for 00.txt 10.txt 20.txt ....   200.txt and 210.txt\n",
    "\n",
    "try:\n",
    "    creds_file = (open(f\"/home/{os.getenv('USER')}/creds.txt\", \"r\")).read().strip().split(\",\")\n",
    "    accesskey,secretkey = creds_file[0],creds_file[1]\n",
    "except:\n",
    "    print(\"File not found, you can't access minio\")\n",
    "    accesskey,secretkey = \"\",\"\"\n",
    "\n",
    "# code to retrieve credentials from creds-mysql.txt\n",
    "\n",
    "try:\n",
    "    mysql_creds_file = (open(f\"/home/{os.getenv('USER')}/creds-mysql.txt\", \"r\")).read().strip().split(\",\")\n",
    "    mysqlaccesskey,mysqlsecretkey = mysql_creds_file[0],mysql_creds_file[1]\n",
    "except:\n",
    "    print(\"File not found, you can't access the mysql server...\")\n",
    "    mysqlaccesskey,mysqlsecretkey = \"\",\"\"\n",
    "\n",
    "\n",
    "conf = SparkConf()\n",
    "conf.set('spark.jars.packages', 'org.apache.hadoop:hadoop-aws:3.2.3,com.mysql:mysql-connector-j:8.3.0')\n",
    "conf.set('spark.hadoop.fs.s3a.aws.credentials.provider', 'org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider')\n",
    "\n",
    "conf.set('spark.hadoop.fs.s3a.access.key', accesskey)\n",
    "conf.set('spark.hadoop.fs.s3a.secret.key', secretkey)\n",
    "# Configure these settings\n",
    "# https://medium.com/@dineshvarma.guduru/reading-and-writing-data-from-to-minio-using-spark-8371aefa96d2\n",
    "conf.set(\"spark.hadoop.fs.s3a.path.style.access\", \"true\")\n",
    "conf.set(\"spark.hadoop.fs.s3a.impl\", \"org.apache.hadoop.fs.s3a.S3AFileSystem\")\n",
    "# https://github.com/minio/training/blob/main/spark/taxi-data-writes.py\n",
    "# https://spot.io/blog/improve-apache-spark-performance-with-the-s3-magic-committer/\n",
    "conf.set('spark.hadoop.fs.s3a.committer.magic.enabled','true')\n",
    "conf.set('spark.hadoop.fs.s3a.committer.name','magic')\n",
    "# Internal IP for S3 cluster proxy\n",
    "conf.set(\"spark.hadoop.fs.s3a.endpoint\", \"http://infra-minio-proxy-vm0.service.consul\")\n",
    "# Send jobs to the Spark Cluster\n",
    "conf.setMaster(\"spark://sm.service.consul:7077\")\n",
    "#Configuration Documentation Link\n",
    "#https://spark.apache.org/docs/latest/configuration.html\n",
    "# Set driver memory\n",
    "conf.set(\"spark.driver.memory\",\"4g\")\n",
    "# Set memory request per executor\n",
    "conf.set(\"spark.executor.memory\",\"8g\")\n",
    "# Set number of cores per executor to 1\n",
    "conf.set(\"spark.executor.cores\",\"1\")\n",
    "# Set number of cores total max per job\n",
    "conf.set(\"spark.cores.max\",\"36\")\n",
    "\n",
    "spark = SparkSession.builder.appName(\"KKcode\")\\\n",
    "    .config('spark.driver.host','spark-edge.service.consul').config(conf=conf).getOrCreate()\n",
    "\n",
    "spark.conf.set(\"spark.sql.debug.maxToStringFields\", 100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4bf87715",
   "metadata": {},
   "outputs": [],
   "source": [
    "from pyspark.sql.types import *\n",
    "from pyspark.sql.functions import *\n",
    "\n",
    "# Read 50.txt from MinIO\n",
    "df = spark.read.csv(\"s3a://itmd521/50.txt\")\n",
    "\n",
    "# Clean and transform data\n",
    "splitDF = df.withColumn('WeatherStation', df['_c0'].substr(5, 6)) \\\n",
    "    .withColumn('WBAN', df['_c0'].substr(11, 5)) \\\n",
    "    .withColumn('ObservationDate', to_date(df['_c0'].substr(16, 8), 'yyyyMMdd')) \\\n",
    "    .withColumn('ObservationHour', df['_c0'].substr(24, 4).cast(IntegerType())) \\\n",
    "    .withColumn('Latitude', df['_c0'].substr(29, 6).cast('float') / 1000) \\\n",
    "    .withColumn('Longitude', df['_c0'].substr(35, 7).cast('float') / 1000) \\\n",
    "    .withColumn('Elevation', df['_c0'].substr(47, 5).cast(IntegerType())) \\\n",
    "    .withColumn('WindDirection', df['_c0'].substr(61, 3).cast(IntegerType())) \\\n",
    "    .withColumn('WDQualityCode', df['_c0'].substr(64, 1).cast(IntegerType())) \\\n",
    "    .withColumn('SkyCeilingHeight', df['_c0'].substr(71, 5).cast(IntegerType())) \\\n",
    "    .withColumn('SCQualityCode', df['_c0'].substr(76, 1).cast(IntegerType())) \\\n",
    "    .withColumn('VisibilityDistance', df['_c0'].substr(79, 6).cast(IntegerType())) \\\n",
    "    .withColumn('VDQualityCode', df['_c0'].substr(86, 1).cast(IntegerType())) \\\n",
    "    .withColumn('AirTemperature', df['_c0'].substr(88, 5).cast('float') / 10) \\\n",
    "    .withColumn('ATQualityCode', df['_c0'].substr(93, 1).cast(IntegerType())) \\\n",
    "    .withColumn('DewPoint', df['_c0'].substr(94, 5).cast('float')) \\\n",
    "    .withColumn('DPQualityCode', df['_c0'].substr(99, 1).cast(IntegerType())) \\\n",
    "    .withColumn('AtmosphericPressure', df['_c0'].substr(100, 5).cast('float') / 10) \\\n",
    "    .withColumn('APQualityCode', df['_c0'].substr(105, 1).cast(IntegerType())) \\\n",
    "    .drop('_c0')\n",
    "\n",
    "splitDF.printSchema()\n",
    "splitDF.show(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3ce718d6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Write cleaned data to MinIO as Parquet\n",
    "splitDF.write.mode(\"overwrite\").parquet(\"s3a://ksaravanan1/fifty.parquet\")\n",
    "\n",
    "# Write cleaned data to MySQL\n",
    "splitDF.write.mode(\"overwrite\").format(\"jdbc\") \\\n",
    "    .option(\"url\", \"jdbc:mysql://infra-database-vm0.service.consul:3306/ksaravanan1\") \\\n",
    "    .option(\"driver\", \"com.mysql.cj.jdbc.Driver\") \\\n",
    "    .option(\"dbtable\", \"fifty\") \\\n",
    "    .option(\"user\", mysqlaccesskey) \\\n",
    "    .option(\"password\", mysqlsecretkey) \\\n",
    "    .save()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b78503db",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# Read back from Parquet (MinIO)\n",
    "minioDF = spark.read.parquet(\"s3a://ksaravanan1/fifty.parquet\")\n",
    "\n",
    "# Read back from MySQL\n",
    "mysqlDF = spark.read.format(\"jdbc\") \\\n",
    "    .option(\"url\", \"jdbc:mysql://infra-database-vm0.service.consul:3306/ksaravanan1\") \\\n",
    "    .option(\"driver\", \"com.mysql.cj.jdbc.Driver\") \\\n",
    "    .option(\"dbtable\", \"fifty\") \\\n",
    "    .option(\"user\", mysqlaccesskey) \\\n",
    "    .option(\"password\", mysqlsecretkey) \\\n",
    "    .load()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5c05b54f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Split data by hemisphere\n",
    "northDF = splitDF.filter(col(\"Latitude\") >= 0)\n",
    "southDF = splitDF.filter(col(\"Latitude\") < 0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0313f1e2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Write to MinIO\n",
    "northDF.write.mode(\"overwrite\").parquet(\"s3a://ksaravanan1/fifty-northern.parquet\")\n",
    "southDF.write.mode(\"overwrite\").parquet(\"s3a://ksaravanan1/fifty-southern.parquet\")\n",
    "\n",
    "# Write to MySQL\n",
    "northDF.write.mode(\"overwrite\").format(\"jdbc\") \\\n",
    "    .option(\"url\", \"jdbc:mysql://infra-database-vm0.service.consul:3306/ksaravanan1\") \\\n",
    "    .option(\"driver\", \"com.mysql.cj.jdbc.Driver\") \\\n",
    "    .option(\"dbtable\", \"fifty-northern\") \\\n",
    "    .option(\"user\", mysqlaccesskey) \\\n",
    "    .option(\"password\", mysqlsecretkey) \\\n",
    "    .save()\n",
    "\n",
    "southDF.write.mode(\"overwrite\").format(\"jdbc\") \\\n",
    "    .option(\"url\", \"jdbc:mysql://infra-database-vm0.service.consul:3306/ksaravanan1\") \\\n",
    "    .option(\"driver\", \"com.mysql.cj.jdbc.Driver\") \\\n",
    "    .option(\"dbtable\", \"fifty-southern\") \\\n",
    "    .option(\"user\", mysqlaccesskey) \\\n",
    "    .option(\"password\", mysqlsecretkey) \\\n",
    "    .save()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6fa9eea3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Stop Spark session\n",
    "spark.stop()"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
